### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by todd7** [todd7/memory-game#1]
### Start

- [x] Create html template v1.

---

### Core

- [ ] Method to shuffle pairs.
- [ ] Method to create cards.
- [ ] Method to check match.

---

### Extra

- [ ] Add score.
- [ ] Method to reset game.
